### PR TITLE
fix(modbus): wrong data transmission

### PR DESCRIPTION
**Pull request by thxCode**
**Fixes:**

#139

**Problem:**

There are some issues in Modbus adaptor implement:
1. Doesn't support float data transmission.
1. Doesn't support detailed type as int16/int32.
1. The `string` type is not a meaningful definition.
1. The byte order of register value cannot be specified.
1. The observed value after operated is confused, for example, if we specify a read-only property as below:
    ```
    spec:
      property:
        name: a
        type: int
        operation: divide 100
    ```
    if the source value of property`a` is `100`, then we may get the status like:
    ```
    status:
      property:
        name: a
        type: int
        operation: divide 100
        value: 0.01
    ```
    as you saw, `0.0.1` wasn't an `int` value.

**Solution:**

1. Introduced new detailed types and replace the `string` value with `hexString`, the following type table shows the changed.

    Name | Type | Bits
    ---|---|---
    `int16` | integer | 16
    `int`, `int32` | integer | 32
    `int64` | integer | 64
    `uint16` | unsigned integer | 16
    `uint`, `uint32` | unsigned integer | 32
    `uint64` | unsigned integer | 64
    `float`, `float32` | float | 32
    `double` | float | 64
    `boolean` | bool | 1
    `hexString` | hex in string, like `CD01` | * 

1. Strengthen the validation of register type and quantity number.

    1. Writable property

        Register | Quantity | Supported Type | Bits
        ---|---|---|---
        `CoilRegister` | 1 | `boolean` | 1
        `CoilRegister` | N | `hexString` | *
        `HoldingRegister` | 1 | `hexString`, `int16`, `uint16` | 16
        `HoldingRegister` | 2 | `int`, `int32`, `uint`, `uint32`, `float` | 32
        `HoldingRegister` | 4 | `int64`, `uint64`, `double` | 64

    1. Readable property

        Register | Quantity | Supported Type | Bits
        ---|---|---|---
        `CoilRegister`, `DiscreteInputRegister` | 1 | `boolean` | 1
        `CoilRegister`, `DiscreteInputRegister` | N | `hexString` | *
        `HoldingRegister`, `InputRegister` | 1 | `hexString`, `int16`, `uint16` | 16
        `HoldingRegister`, `InputRegister` | 2 | `int`, `int32`, `uint`, `uint32`, `float` | 32
        `HoldingRegister`, `InputRegister` | 4 | `int64`, `uint64`, `double` | 64

    > Octopus UI needs to validate as above.

1. Introduced a new field `endianness` to specify the byte order of register value, the default value is `BigEndian`

    1. `CoilRegister` and `DiscreteInputRegister` don't need to configure `endianness`.

    1. `HoldingRegister` and `InputRegister` are support to configure `endianness`, but it must ensure the byte order manually when writing a value via `hexString`.

1. Introduced a new field `operatedValue` to describe the value after operated.

**Test plan:**

None

### CODE REVIEW

**Comment by thxCode** [comment]
This PR includes the fix of https://github.com/cnrancher/octopus/pull/140.

**Review by guangbochen — COMMENTED** [review]
having two questions in regards to the PR change:
1. how will this reflecting the existing Modbus devices, does the user requires to re-deploy the modbusDevice or they can modify it?
2. does it require any UI design changes?

**Comment by thxCode** [comment]
1. I have remarked the BREAKING CHANGE in the comment, this PR doesn't change the existing health Modbus device without any `string` properties. 
1. This absolutely needs a change in UI. The UI should allow the new property types and give a place to show the `operatedValue`.

There are many details in the change of UI, I prefer to communicate with @WuJun2016 offline.

**Review by guangbochen — APPROVED** [review]
LGTM, and since PR this only requires removing the `string` data type in the UI so we will merge this PR first and fix the UI accordingly, thanks.

**Pull request merged**
